# Using default color theme.

# white on black
#background: #000000
#foreground: #ffffff
#cursor: #22ff22

# green on black
background: #000000
foreground: #00ff00
#cursor: #00ff00
cursor: #ffffff

#background: #cce8cf
#foreground: #000000
#cursor: #ffffff
