prompt_batemp() {
  local -i len=$#_p9k__prompt _p9k__has_upglob
  _p9k_prompt_segment $0 green black '' 1 '$_p9k__batemp' '$_p9k__batemp°C'
  (( _p9k__has_upglob )) || typeset -g "_p9k__segment_val_${_p9k__prompt_side}[_p9k__segment_index]"=$_p9k__prompt[len+1,-1]
}

function _p9k_prompt_batemp_init() {
  if [[ $+commands[adb] == 0 ]]; then
    typeset -g "_p9k__segment_cond_${_p9k__prompt_side}[_p9k__segment_index]"='${:-}'
    return
  fi
  typeset -g _p9k__batemp=
  _p9k__async_segments_compute+='_p9k_worker_invoke batemp _p9k_prompt_batemp_compute'
}

_p9k_prompt_batemp_compute() {
  _p9k_worker_async _p9k_prompt_batemp_async _p9k_prompt_batemp_sync
}

_p9k_prompt_batemp_async() {
  local msg && msg="$(adb shell dumpsys battery 2>/dev/null|grep temperature|awk -F':' '{print int($2/10)}')"
  _p9k__batemp=$msg
  _p9k_print_params _p9k__batemp
  echo -E - 'reset=1'
}

_p9k_prompt_batemp_sync() {
  eval $REPLY
  _p9k_worker_reply $REPLY
}


 POWERLEVEL9K_MODE="nerdfont-complete"
 POWERLEVEL9K_ICON_PADDING=none
 POWERLEVEL9K_ICON_BEFORE_CONTENT=true
#POWERLEVEL9K_MODE="awesome-patched"
#POWERLEVEL9K_DISABLE_RPROMPT=true
#POWERLEVEL9K_RPROMPT_ON_NEWLINE=true
#POWERLEVEL9K_PROMPT_ON_NEWLINE=true
#POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
 POWERLEVEL9K_TRANSIENT_PROMPT=always
 POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=" "
#POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=""
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="❯"
#POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="  %F{cyan}\uf120%f"
 POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%F{red}(ง •̀_•́)ง%f" #"👽🔞🍉➜❯ " #" ➜ †♥囍ꍄ"❯
 POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='·'
 POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=234
 POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=244
 POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
 POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
 POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='│'  #
 POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='│'  #
 POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='▓▒░'
 POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='░▒▓'
 POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
 POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
 POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=''
 POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
     custom_icon
     #os_icon
     dir
     dir_writable
     #root_indicator
     #vcs
     newline
     #prompt_char
 )
 POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
     status
     command_execution_time
     background_jobs
     #history
     #battery
     #battery_temperature
     batemp
     #load
     ram
     time
 )
 POWERLEVEL9K_CUSTOM_ICON="echo ' '" #    "    echo -e "\uf302"
 POWERLEVEL9K_CUSTOM_ICON_BACKGROUND="032"
 POWERLEVEL9K_CUSTOM_ICON_FOREGROUND="015"
 POWERLEVEL9K_OS_ICON_BACKGROUND="032"
 POWERLEVEL9K_OS_ICON_FOREGROUND="015"
#POWERLEVEL9K_DISABLE_GITSTATUS=1
#POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=1
 POWERLEVEL9K_DIR_FOREGROUND=silver
 POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE_ALWAYS=true
 POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=silver
 POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=240
 POWERLEVEL9K_STATUS_OK=1
 POWERLEVEL9K_STATUS_VERBOSE=1
 POWERLEVEL9K_STATUS_OK_IN_NON_VERBOSE=1
 POWERLEVEL9K_STATUS_EXTENDED_STATES=1
 POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=1
 POWERLEVEL9K_STATUS_ERROR_FOREGROUND=yellow
 POWERLEVEL9K_STATUS_ERROR_BACKGROUND=red
 POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_last' # ""
 POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"
 POWERLEVEL9K_TIME_FOREGROUND=black
 POWERLEVEL9K_TIME_BACKGROUND=069
 POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION=''
#POWERLEVEL9K_RAM_FOREGROUND=silver
 POWERLEVEL9K_RAM_VISUAL_IDENTIFIER_EXPANSION=''
#POWERLEVEL9K_LOAD_FOREGROUND=silver
 POWERLEVEL9K_LOAD_VISUAL_IDENTIFIER_EXPANSION=''
#POWERLEVEL9K_HISTORY_FOREGROUND=silver
 POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT="dhms"
 POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=black
 POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=202
 POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION=""
 POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
